In [1]:
import numpy as np

In [2]:
x = np.array([[0, 1], [2, 3], [4, 5]])
x.tolist()

[[0, 1], [2, 3], [4, 5]]

In [3]:
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
s = 0
for i in range(min(x.shape)):
    s+= x[i, i]
    
s

15

In [5]:
x.trace()

15

In [6]:
x = np.random.randint(1, 10, size=(3, 3))
x

array([[1, 1, 6],
       [9, 3, 5],
       [6, 6, 6]])

In [7]:
x[x > 5]

array([6, 9, 6, 6, 6])

In [8]:
a = np.random.randint(1, 10, size=(3, 3))
b = np.random.randint(1, 10, size=(3, 3))
print(a)
print('\n')
print(b)

[[4 7 6]
 [5 2 3]
 [4 3 3]]


[[6 7 1]
 [8 3 3]
 [2 1 8]]


In [9]:
a+b

array([[10, 14,  7],
       [13,  5,  6],
       [ 6,  4, 11]])

In [10]:
c = np.zeros(a.shape)
for i in range(a.shape[0]):
    for j in range(a.shape[1]):
        c[i, j] = a[i, j]
        c[i, j] += b[i, j]
c

array([[10., 14.,  7.],
       [13.,  5.,  6.],
       [ 6.,  4., 11.]])

In [11]:
x = np.random.random((5, 3))
x, x.mean(axis=1)

(array([[0.9202186 , 0.46721661, 0.47888194],
        [0.1182639 , 0.66552257, 0.96471714],
        [0.50653703, 0.39272106, 0.77390366],
        [0.92494887, 0.50822848, 0.64774402],
        [0.25200576, 0.08797069, 0.77844429]]),
 array([0.62210572, 0.58283454, 0.55772058, 0.69364046, 0.37280692]))

In [12]:
x - x.mean(axis=1)[:, np.newaxis]

array([[ 0.29811288, -0.15488911, -0.14322378],
       [-0.46457064,  0.08268803,  0.3818826 ],
       [-0.05118355, -0.16499953,  0.21618308],
       [ 0.23130841, -0.18541197, -0.04589644],
       [-0.12080116, -0.28483622,  0.40563738]])